services:
  backend:
    tty: true
    build: 
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    container_name: go_server
    environment: 
      DB_HOST: db
    networks:
      docker-network:
        ipv4_address: 172.20.0.3
    ports:
      - "1234:1234"
    env_file:
      - .env
    depends_on: 
      db:
        condition: service_healthy

  db:
    container_name: postgres_db
    image: postgres:16.2
    platform: linux/amd64
    networks:
      docker-network:
        ipv4_address: 172.20.0.4
    volumes:
      - postgres_volume:/var/lib/mysql
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
      POSTGRES_DB: test
    healthcheck:
      test: ["CMD-SHELL", "sh -c 'pg_isready -U ${DB_USER} -d ${DB_NAME}'"]
      interval: 5s
      timeout: 5s
      retries: 5
volumes:
    postgres_volume: { }
networks:
  docker-network:
      external: true
    


